micronaut:
  application:
    name: cdsi
  executors:
    enclave-jni:
      type: scheduled
      core-pool-size: 1
  metrics:
    enabled: true
    export:
      statsd:
        enabled: true
  server:
    port: 8080  # Main server port
    netty:
      compression-threshold: 1073741824
      compression-level: 0

# Endpoint configuration
endpoints:
  all:
    port: 8081

# Cosmos DB Configuration for rate limiting
cosmos:
  database: <your-cosmos-db-name>
  container: <your-container-name>
  endpoint: "https://<your-cosmos-instance>.documents.azure.com:443"
  key: <your-cosmos-key>

# Redis Configuration for connection rate limiting
redis:
  uris: redis://<your-redis-host>

# Account data source configuration
accountTable:
  region: <your-aws-region>
  tableName: <your-dynamodb-table>
  streamName: <your-kinesis-stream>

# Authentication configuration
authentication:
  sharedSecret: <your-base64-encoded-32-byte-secret>

# Enclave configuration
enclave:
  enclaveId: <your-enclave-id>
  availableEpcMemory: 32000000
  loadFactor: 1.6
  shards: 1
  token-secret: <your-token-secret>
  simulated: false

leakyBucketLimit:
  connections:
    bucket-size: 10
    leak-rate-scalar: 10
    leak-rate-duration: PT1M

tokenRateLimit:
  bucket-size: 50000
  leak-rate-scalar: 6
  leak-rate-duration: PT1H

logger:
  levels:
    com.azure.cosmos: WARN